### ISSUE TITLE
Lora Nodes communication without using internet

### ISSUE THREAD

**Issue by turkone** [ricaun/LoRaNow#8]
First of all i would like to thank you for all your studies. 
I want to make the lora nodes network(more than 5 nodes) those have their id and communicate with each other without using internet. I am using just LoRa Ra-02  SX1278 433 Mhz modules and Arduino Unos .Could you help me?

**Comment by ricaun** [comment]
Hello,
You need to have a gateway to receive de messages if your gateway has internet is easier to control and send forward the nodes messages.
But you need to remember the node only receives a message after sends to the gateway.
The library was not designed to make a mesh network or make all the nodes talk with each other.
You need to have a gateway.
See yea!

**Comment by turkone** [comment]
thanks for the answer .I got one more question.
I use two SX1278 LoRa Ra-02 modules for communication. I wonder how I can set IDs for these two modules to deny an interference with other LoRa modules which work at the same frequency.

I mean, is there a solution similar to pipe addresses of NRF24l01 communication. Thanks in advance.

**Comment by ricaun** [comment]
I really don't know hot the pipe addresses of NRF24l01 works, if you need to set the ID of the node you can use this function `LoRaNow.setId(id);`, the library already deny any random packages how is not looks like the loranow protocol.

**Comment by turkone** [comment]
That will be useful for my problem. Thanks a lot .
